import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import 'aop_generator.dart';
import 'service_autoscan.dart';

/// 创建AOP生成器的Builder
Builder aopGenerator(BuilderOptions options) {
  return LibraryBuilder(AopGenerator(), generatedExtension: '.g.dart');
}

Builder serviceAutoScan(BuilderOptions options) {
  return PartBuilder(
    [ServiceAutoScan()],
    '.g.dart',
    header: '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Service auto-scan implementation generated by fall_core_gen

''',
    options: options,
  );
}
