# Fall Core Example Build Configuration
targets:
  $default:
    builders:
      # Fall Core AOP代码生成器
      fall_core|aop_generator:
        enabled: true
        generate_for:
          - lib/**
      
      # Fall Core服务生成器
      fall_core|service_generator:
        enabled: true
        generate_for:
          - lib/**