targets:
  $default:
    builders:
      fall_core|aop_generator:
        enabled: true
        generate_for:
          - lib/**
      fall_core|service_generator:
        enabled: true
        generate_for:
          - lib/**

builders:
  aop_generator:
    import: "package:fall_core/src/generators/aop_generator.dart"
    builder_factories: ["aopGenerator"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    
  service_generator:
    import: "package:fall_core/src/generators/service_generator.dart"
    builder_factories: ["serviceGenerator"]
    build_extensions: {"$lib$": ["init/auto_scan.g.dart"]}
    auto_apply: dependents
    build_to: source