name: fall_core
description: "Fall Core - A Flutter AOP and Dependency Injection framework inspired by Spring, providing enterprise-level DI and AOP capabilities."
version: 0.0.5
homepage: https://github.com/flutter-fall/fall_core
repository: https://github.com/flutter-fall/fall_core
issue_tracker: https://github.com/flutter-fall/fall_core/issues

# Topics help users discover your package on pub.dev
topics:
  - aop
  - dependency-injection
  - spring
  - framework

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '>=3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  logger: ^2.6.1
  meta: ^1.15.0
  path: ^1.9.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

