name: fall_core
description: "Fall Core - A Flutter AOP and Dependency Injection framework inspired by Spring, providing enterprise-level DI and AOP capabilities."
version: 0.0.1
homepage: https://github.com/flutter-fall/fall_core
          https://gitee.com/fall-flutter/fall_core
repository: https://github.com/flutter-fall/fall_core
issue_tracker: https://github.com/flutter-fall/fall_core/issues

# Topics help users discover your package on pub.dev
topics:
  - flutter
  - aop
  - dependency-injection
  - spring
  - framework
  - enterprise

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '>=3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  # GetX for state management and dependency injection
  get: ^4.7.2
  
  # Logger for logging capabilities
  logger: ^2.6.1
  
  # Annotations for code generation
  meta: ^1.15.0
  
  # Code generation dependencies (required for lib/ usage)
  build: ^3.0.2
  source_gen: ^3.1.0
  analyzer:  ^7.5.5 
  glob: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules
  flutter_lints: ^5.0.0
  
  # Build runner for development
  build_runner: ^2.7.0


