name: fall_core_base
description: "Fall Core Base - Core annotations and utilities for Fall Core framework. Provides @Service, @Auto, @Aop annotations and basic utilities."
version: 0.0.4
homepage: https://github.com/flutter-fall/fall_core
repository: https://github.com/flutter-fall/fall_core
issue_tracker: https://github.com/flutter-fall/fall_core/issues

# Topics help users discover your package on pub.dev
topics:
  - annotations
  - aop
  - dependency-injection
  - framework
  - utilities

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '>=3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# 核心库保持零外部依赖（除Flutter SDK外）以实现轻量化设计
dependencies:
  flutter:
    sdk: flutter
  # 元数据注解支持
  meta: ^1.15.0
  # 日志支持
  logger: ^2.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

